#!/bin/bash
# ┳┓          ┓   ┏┓       
# ┃┃┏┓╋┓┏┏┏┓┏┓┃┏  ┗┓╋┏┓╋┓┏┏
# ┛┗┗ ┗┗┻┛┗┛┛ ┛┗  ┗┛┗┗┻┗┗┻┛
#
# Monitors network status.
# Most of the code copied from https://github.com/linkfrg/dotfiles/blob/eww/.config/eww/scripts/network.sh
# (Thank you, linkfrg!)

get_network_status ()
{
    signal=$(nmcli -f in-use,signal dev wifi | rg "\*" | awk '{ print $2 }')
    essid=$(nmcli -t -f NAME connection show --active | head -n1 | sed 's/\"/\\"/g')
    vpn=$(nmcli con show --active | grep -e tun -e vpn | wc -c)
    if [[ $vpn -ne 0 ]]; then
        vpn="true"
    else
        vpn="false"
    fi
    echo '{"essid": "'"$essid"'", "signal": "'"$signal"'", "vpn": '$vpn'}'
}

get_network_status
ip monitor link | while read -r line; do 
    get_network_status
done

